// Generated by Framer
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, getFonts, getLoadingLazyAtYPosition, Image, RichText, SmartComponentScopedContainer, SVG, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const cycleOrder = ["SpsH3oYwX", "mRKQkSXfK", "g_VDVmccA"];
const serializationHash = "framer-HealthcareHero";
const variantClassNames = { g_VDVmccA: "framer-v-phone", mRKQkSXfK: "framer-v-tablet", SpsH3oYwX: "framer-v-desktop" };

function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}

const transition1 = { bounce: .2, delay: 0, duration: .4, type: "spring" };
const animation = { opacity: .7, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, transition: transition1 };

const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /*#__PURE__*/_jsx(MotionConfigContext.Provider, { value: contextValue, children: children });
};

const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "SpsH3oYwX", Phone: "g_VDVmccA", Tablet: "mRKQkSXfK" };

const getProps = ({ height, id, width, ...props }) => {
  return { ...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "SpsH3oYwX" };
};

const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};

const Component = /*#__PURE__*/React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "SpsH3oYwX", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);

  return /*#__PURE__*/_jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/_jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/_jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/_jsxs(Image, {
          ...restProps,
          ...gestureHandlers,
          background: {
            alt: "Healthcare background",
            fit: "fill",
            loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
            pixelHeight: 1080,
            pixelWidth: 1920,
            positionX: "center",
            positionY: "center",
            sizes: componentViewport?.width || "100vw",
            src: "https://framerusercontent.com/images/healthcare_hero_bg.jpeg", // Placeholder image URL, replace with an actual green-themed healthcare image
            srcSet: "https://framerusercontent.com/images/healthcare_hero_bg.jpeg?scale-down-to=1024 1024w,https://framerusercontent.com/images/healthcare_hero_bg.jpeg?scale-down-to=2048 2048w,https://framerusercontent.com/images/healthcare_hero_bg.jpeg 1920w"
          },
          className: cx(scopingClassNames, "framer-45aawe", className, classNames),
          "data-framer-name": "Hero Section",
          layoutDependency: layoutDependency,
          layoutId: "SpsH3oYwX",
          ref: refBinding,
          style: { ...style, backgroundColor: "rgb(152, 217, 186)" }, // Green background color
          ...addPropertyOverrides({ g_VDVmccA: { "data-framer-name": "Phone" }, mRKQkSXfK: { "data-framer-name": "Tablet" } }, baseVariant, gestureVariant),
          children: [
            /*#__PURE__*/_jsxs(motion.div, {
              className: "framer-content-container",
              "data-framer-name": "Content Container",
              layoutDependency: layoutDependency,
              layoutId: "content-container",
              children: [
                /*#__PURE__*/_jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/_jsx(React.Fragment, {
                    children: /*#__PURE__*/_jsx(motion.p, {
                      style: {
                        "--font-selector": "InterDisplay-Medium",
                        "--framer-font-family": '"Inter Display", sans-serif',
                        "--framer-font-size": "18px",
                        "--framer-font-weight": "500",
                        "--framer-letter-spacing": "0.01em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-alignment": "center",
                        "--framer-text-color": "rgb(255, 255, 255)"
                      },
                      children: "Your Health, Our Priority"
                    })
                  }),
                  className: "framer-top-text",
                  "data-framer-name": "Top Text",
                  fonts: ["FR;InterDisplay-Medium"],
                  layoutDependency: layoutDependency,
                  layoutId: "top-text",
                  style: { "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides({ g_VDVmccA: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.p, { style: { "--framer-font-size": "16px" }, children: "Your Health, Our Priority" }) }) }, mRKQkSXfK: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.p, { style: { "--framer-font-size": "17px" }, children: "Your Health, Our Priority" }) }) } }, baseVariant, gestureVariant)
                }),
                /*#__PURE__*/_jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/_jsx(React.Fragment, {
                    children: /*#__PURE__*/_jsx(motion.h1, {
                      style: {
                        "--font-selector": "Familjen Grotesk-italic",
                        "--framer-font-family": '"Familjen Grotesk", sans-serif',
                        "--framer-font-size": "90px",
                        "--framer-font-style": "italic",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1em",
                        "--framer-text-alignment": "center",
                        "--framer-text-color": "rgb(255, 255, 255)"
                      },
                      children: "Seamless Healthcare, In Your Pocket."
                    })
                  }),
                  className: "framer-heading",
                  "data-framer-name": "Heading",
                  fonts: ["FS;Familjen Grotesk-italic"],
                  layoutDependency: layoutDependency,
                  layoutId: "heading",
                  style: { "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides({ g_VDVmccA: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.h1, { style: { "--framer-font-size": "48px" }, children: "Seamless Healthcare, In Your Pocket." }) }) }, mRKQkSXfK: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.h1, { style: { "--framer-font-size": "64px" }, children: "Seamless Healthcare, In Your Pocket." }) }) } }, baseVariant, gestureVariant)
                }),
                /*#__PURE__*/_jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/_jsx(React.Fragment, {
                    children: /*#__PURE__*/_jsx(motion.p, {
                      style: {
                        "--font-selector": "InterDisplay-Regular",
                        "--framer-font-family": '"Inter Display", sans-serif',
                        "--framer-font-size": "20px",
                        "--framer-letter-spacing": "0em",
                        "--framer-line-height": "1.5em",
                        "--framer-text-alignment": "center",
                        "--framer-text-color": "rgb(255, 255, 255)"
                      },
                      children: "Manage appointments, prescriptions, and health records with ease. Connect with trusted doctors anytime, anywhere."
                    })
                  }),
                  className: "framer-description",
                  "data-framer-name": "Description",
                  fonts: ["FR;InterDisplay"],
                  layoutDependency: layoutDependency,
                  layoutId: "description",
                  style: { "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                  ...addPropertyOverrides({ g_VDVmccA: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.p, { style: { "--framer-font-size": "16px" }, children: "Manage appointments, prescriptions, and health records with ease. Connect with trusted doctors anytime, anywhere." }) }) }, mRKQkSXfK: { children: /*#__PURE__*/_jsx(React.Fragment, { children: /*#__PURE__*/_jsx(motion.p, { style: { "--framer-font-size": "18px" }, children: "Manage appointments, prescriptions, and health records with ease. Connect with trusted doctors anytime, anywhere." }) }) } }, baseVariant, gestureVariant)
                }),
                /*#__PURE__*/_jsxs(motion.div, {
                  className: "framer-button",
                  "data-framer-name": "Call to Action Button",
                  layoutDependency: layoutDependency,
                  layoutId: "call-to-action-button",
                  style: { backgroundColor: "rgb(255, 255, 255)", borderRadius: "40px", padding: "16px 32px" },
                  whileHover: animation,
                  children: [
                    /*#__PURE__*/_jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/_jsx(React.Fragment, {
                        children: /*#__PURE__*/_jsx(motion.p, {
                          style: {
                            "--font-selector": "InterDisplay-SemiBold",
                            "--framer-font-family": '"Inter Display", sans-serif',
                            "--framer-font-weight": "600",
                            "--framer-text-color": "rgb(0, 128, 0)" // Dark green text for button
                          },
                          children: "Download Now"
                        })
                      }),
                      className: "framer-button-text",
                      "data-framer-name": "Button Text",
                      fonts: ["FR;InterDisplay-SemiBold"],
                      layoutDependency: layoutDependency,
                      layoutId: "button-text",
                      style: { "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" },
                      verticalAlignment: "top",
                      withExternalLayout: true
                    }),
                    /*#__PURE__*/_jsx(motion.div, {
                      className: "framer-icon-wrapper",
                      "data-framer-name": "Icon Wrapper",
                      layoutDependency: layoutDependency,
                      layoutId: "icon-wrapper",
                      style: { backgroundColor: "rgb(0, 128, 0)", borderRadius: "50%", padding: "8px" }, // Dark green background for icon
                      children: /*#__PURE__*/_jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/_jsx(SmartComponentScopedContainer, {
                          className: "framer-icon-container",
                          isAuthoredByUser: true,
                          isModuleExternal: true,
                          layoutDependency: layoutDependency,
                          layoutId: "icon-container",
                          nodeId: "icon-node",
                          rendersWithMotion: true,
                          scopeId: "healthcare-icon-scope",
                          children: /*#__PURE__*/_jsx(SVG, {
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>', // Arrow right icon
                            style: { width: "20px", height: "20px", color: "rgb(255, 255, 255)" } // White icon color
                          })
                        })
                      })
                    })
                  ]
                })
              ]
            })
          ]
        })
      })
    })
  });
});

const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  `.framer-HealthcareHero.framer-45aawe {
    align-content: center;
    align-items: center;
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    gap: 10px;
    height: 760px; /* Adjust height as needed */
    justify-content: center;
    overflow: hidden;
    padding: 80px;
    position: relative;
    width: 100%;
  }`,
  `.framer-HealthcareHero .framer-content-container {
    align-content: center;
    align-items: center;
    display: flex;
    flex: 1 0 0px;
    flex-direction: column;
    flex-wrap: nowrap;
    height: min-content;
    justify-content: center;
    max-width: 900px;
    min-height: 400px;
    overflow: hidden;
    padding: 0px;
    position: relative;
    width: 1px;
    z-index: 2;
    gap: 24px;
  }`,
  `.framer-HealthcareHero .framer-top-text, .framer-HealthcareHero .framer-button-text {
    flex: none;
    height: auto;
    position: relative;
    white-space: pre;
    width: auto;
  }`,
  `.framer-HealthcareHero .framer-heading {
    --framer-text-wrap: balance;
    flex: 1 0 0px;
    height: auto;
    position: relative;
    white-space: pre-wrap;
    width: 100%;
    word-break: break-word;
    word-wrap: break-word;
  }`,
  `.framer-HealthcareHero .framer-description {
    flex: none;
    height: auto;
    position: relative;
    white-space: pre-wrap;
    width: 80%;
    word-break: break-word;
    word-wrap: break-word;
  }`,
  `.framer-HealthcareHero .framer-button {
    align-content: center;
    align-items: center;
    cursor: pointer;
    display: flex;
    flex: none;
    flex-direction: row;
    flex-wrap: nowrap;
    gap: 12px;
    height: min-content;
    justify-content: center;
    overflow: hidden;
    position: relative;
    width: min-content;
    will-change: var(--framer-will-change-effect-override, transform);
  }`,
  `.framer-HealthcareHero .framer-icon-wrapper {
    align-content: center;
    align-items: center;
    display: flex;
    flex: none;
    flex-direction: row;
    flex-wrap: nowrap;
    gap: 10px;
    height: min-content;
    justify-content: center;
    overflow: hidden;
    position: relative;
    width: min-content;
    will-change: var(--framer-will-change-override, transform);
  }`,
  `.framer-HealthcareHero .framer-icon-container {
    flex: none;
    height: 16px;
    position: relative;
    width: 16px;
  }`,
  // Tablet adjustments
  `.framer-HealthcareHero.framer-v-tablet.framer-45aawe {
    padding: 60px 30px;
    height: 600px;
  }`,
  `.framer-HealthcareHero.framer-v-tablet .framer-heading {
    font-size: 64px !important;
  }`,
  `.framer-HealthcareHero.framer-v-tablet .framer-description {
    width: 90%;
  }`,
  // Phone adjustments
  `.framer-HealthcareHero.framer-v-phone.framer-45aawe {
    padding: 40px 16px;
    height: 500px;
  }`,
  `.framer-HealthcareHero.framer-v-phone .framer-heading {
    font-size: 48px !important;
    text-align: center;
  }`,
  `.framer-HealthcareHero.framer-v-phone .framer-description {
    width: 100%;
    text-align: center;
  }`,
];

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 760
 * @framerIntrinsicWidth 1350
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"mRKQkSXfK":{"layout":["fixed","auto"]},"g_VDVmccA":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerHealthcareHero = withCSS(Component, css, "framer-HealthcareHero");

export default FramerHealthcareHero;

FramerHealthcareHero.displayName = "Healthcare Hero Section";
FramerHealthcareHero.defaultProps = { height: 760, width: 1350 };

addPropertyControls(FramerHealthcareHero, {
  variant: {
    options: ["SpsH3oYwX", "mRKQkSXfK", "g_VDVmccA"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum
  }
});

addFonts(FramerHealthcareHero, [
  {
    explicitInter: true,
    fonts: [
      { family: "Inter Display", source: "framer", style: "normal", weight: "500" },
      { family: "Inter Display", source: "framer", style: "normal", weight: "400" },
      { family: "Inter Display", source: "framer", style: "normal", weight: "600" },
    ]
  },
  {
    family: "Familjen Grotesk",
    source: "fontshare",
    style: "italic",
    url: "https://framerusercontent.com/third-party-assets/fontshare/wf/5JFRTGNWRXSPMB5RBUJCJLQPS4INZODV/23JZG4FQ3IF5JQJAAKBH4N7ZN4OT3H7T/IKXAVOBPMOGTW4U57BO664GAWJ2MN4U2.woff2",
    weight: "400"
  },
]);
